[project]
name = "rules-kata"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest==8.3.5",
    "mypy==1.15.0",
    "ruff==0.9.9",
]

[tool.pytest.ini_options]
pythonpath = ["src"]